name: LFmap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - python=3.10

  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.7

  - faiss-gpu

  - matplotlib
  - numpy>=1.24.0
  - pandas
  - matplotlib
  - pip
  - scikit-learn
  - PyYAML

  - tqdm
  - iopath
  - easydict
  - pycocotools
  - pip

  - pip:
    - scared
    - omegaconf
    - regex
    - submitit
    - termcolor
    - torchmetrics
