name: lfmtrans
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - faiss-gpu
  - numpy>=1.24
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pyyaml
  - tqdm
  - iopath
  - easydict
  - pycocotools
  - pillow
  - pip
  - pip:
      - sacred
      - omegaconf
      - regex
      - submitit
      - termcolor
      - torchmetrics
      - pot
      - tiktoken
      - opencv-python
