seed: 2025

device_gpu: 0
save: 1

paths:
  log_root: &log_root ./train_log
  feature_root: &feature_root ./feature
  llama_root: &llama_root ./Meta-Llama-3-8B-Instruct
  checkpoint_subdir: &checkpoint_subdir checkpoints
  one_photo_feature_subdir: &one_photo_feature_subdir features/one_photo
  one_photo_debug_subdir: &one_photo_debug_subdir features/one_photo/debug

dataset:
  resize: 518
  root_dir_mscoco: data/mscoco
  root_dir_ade20k: data/ade20k/
  root_dir_pc: data/pascal_context
  root_dir_voc: data/pascal_voc
  DINOv2_BACKBONE_SIZE: &dino_backbone large   # small, base, large, giant
  val_batch_size: 8
  num_workers: 2

eval:
  DINOv2_BACKBONE_SIZE: *dino_backbone
  input_dim: 4096
  output_dim: 1024
  enabled: 0
  method: LFMTrans   # LFMTrans, uvlt, talk2dino
  checkpoint_path: ''

train:
  dataset: cocostuff
  batchsize: 1
  sample: 20
  text_model: llama_unmean        # llama_unmean, mpnet_unmean, llama, mpnet
  type: patch_unmean              # patch_unmean, patch

knngraph:
  k: 30
  metric_knn: ip                  # ip, L2
  metric_laplacian: sym           # none, sym, rw

laplacian_mat:
  k: 170                          # number of eigenvectors used in decomposition

anchor:
  n_anchors: 50
  cls_anchors: 2
  metric: ip                      # L2 or ip

validation:
  dataset: cocostuff
  datasets: ['cocostuff', '150', 'voc20', 'pc59', 'CIFAR-100', 'ImageNet-100']
  text_model: llama               # llama, mpnet
  type: patch
  shuffle_before_eval: false
  shuffle_trials: 1
  shuffle_seed: 2025

fmap:
  type: train                     # anchor, Ip_and_L2, train, train_one_photo
  method: LFMtrans                # LFMtrans, EOT
  lmbda: 200.0
  aux_lmbda: 10.0
  reg: 1.0e-6
  resolvant_gamma: 0.5

projector:
  hidden_dim: 4096
  dropout: 0.0
  normalize_output: true
  checkpoint_path: ''

projector_train:
  epochs: 20
  steps_per_epoch: 50
  classes_per_step: 16
  samples_per_class: 8
  lr: 1.0e-4
  weight_decay: 1.0e-4
  grad_clip: 2.0
  log_every: 10
  ckpt_dir: *checkpoint_subdir
  report_train_each_epoch: true

  mask: 1                         # 1=original training, 2=cluster training
  cluster_subsample_ratio: 0.5
  cluster_kmeans_n_init: 100
  cluster_remove_zero_padding: true
  cluster_rebuild_each_epoch: false
  report_cluster_each_epoch: true
  kmeans_metric: L2               # ip or L2

loss:
  w_bij: 1.0
  w_orth: 1.0
  w_lap: 1.0e-3
  w_ot: 0.75
  w_proper: 1.0
  temperature: 0.1
  ot_projections: 64
  ot_p: 2
