seed: 2025

deice_gpu: 0
save: 2

anchor:
  n_anchors: 6
  metric: ip # 'L2' or 'ip'

knngraph:
  k: 6
  sigma: 1
  knn_fn: L2 # 'ip' or 'L2'
  W_full_fn: L2 # 'ip' or 'L2'
  W_fn: inv # 'heat_kernel' or 'inv' or 'raw'

laplacian_mat:
  k: 9 # K eigenvectors for using in decomposition

fm_retrieval:
  metric: L2 # 'ip' or 'L2'

model:
  text_dimension: 4096
  vision_dimension: 1024
  DINOv2_BACKBONE_SIZE: large # small, base, large, giant

train:
  samples: 20
  type: prototype # photo, mask, prototype
  dataset: CIFAR-10 # cocostuff, CIFAR-10, CIFAR-100

permute:
  metric: 'L2' # 'ip' or 'L2'