seed: 2025

deice_gpu: 0
save: 54

knngraph:
  k: 50
  sigma: 1
  knn_fn: L2 # 'ip' or 'L2'
  W_full_fn: L2 # 'ip' or 'L2'
  W_fn: raw # 'heat_kernel' or 'inv' or 'raw'

laplacian_mat:
  k: 1000 # K eigenvectors for using in decomposition

fm_retrieval:
  metric: L2 # 'ip' or 'L2'

model:
  text_dimension: 4096
  vision_dimension: 1024
  nums_epoch_proj: 1000

  lr_projector: 0.00005
  DINOv2_BACKBONE_SIZE: large # small, base, large, giant

train:
  batchsize: 1
  samples: 20
  type: photo # photo, mask, prototype
  dataset: cocostuff # cocostuff, CIFAR-10, CIFAR-100

permute:
  metric: 'L2' # 'ip' or 'L2'

loss:
  w_bij: 1.0
  w_orth: 1.0
  w_lap: 0.0
  w_align: 1.0
  w_ot: 100.0
  L_ot: 200
  bidirectional: false
  W_SGW_lossweight: 100.0
  W_SGW_L: 1000
  SGW_bidirectional: false